### ISSUE TITLE
Buy function takes too long

### ISSUE THREAD

**Issue by bressanmarcos** [iqoptionapi/iqoptionapi#8]
When using the following script:
```

iq = IQ_Option('email', 'password')
iq.buy(10, 'EURUSD', 'put', 1)
```
the order takes up to 6-7 seconds to be sent to IQ Option platform.
Is there a way to make it faster, please? 
Maybe a lower level function that can be useful for this... 
I usually get only candles' prices and send orders, perhaps simpler functions could handle this.

Thx!

**Comment by luizmateusramos** [comment]
Hey guys,  i don't know if this issue raised is up to date , but i am facing an issue during the buy method 
it is messaging that the buy was failed , also how the method know that i am buying a Binary Stock rather than Digital?


Galera estou enfrentando um problema quando tendo executar o metódo de compra , ele esta printando o erro de que não foi possível realizar a conta, outra coisa...como o metodo sabe que ao invés de Opcões binarias eu estou comprando digitais?

def comprarPapel(nomePapel,conexao,dinheiro,modoExpiracao):
    print("Comprando " + nomePapel + " Valor:" + str(dinheiro))
    print(conexao.get_candles(nomePapel,60,111,time.time()))

    check,id = conexao.buy(dinheiro,nomePapel,"call",modoExpiracao)
    if check:
        print("Comprado")
    else:
        print("falha na compra")
        print(id)

**Comment by caiowilson** [comment]
você pode definir o tipo de asset para compra com o método:` API.buy_digital_spot()` ou usar o buy_order(instrument_type, instrument_id, side, amount, leverage, type)

agora, o que a função espera só conferindo puxando um binário e olhando o json de respostas. A API tem que ser reformulada e documentada, em breve algumas funções vão estar melhor documentadas.
@luizmateusramos

**Comment by bressanmarcos** [comment]
For the issue raise by me, it was just a time difference between the server timestamp and my PC's. 
Querying the server timestamp before sending any order works just fine.
